# Generated by Django 4.0.4 on 2022-05-31 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogpostApp', '0002_blogpost_create_date_alter_blogpost_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='last_modified',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
