# Generated by Django 4.0.4 on 2022-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogpostApp', '0003_blogpost_last_modified_alter_blogpost_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
